# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - checkout
      # BUILD UP
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install

      # run tests!
      - run: npm install
      - run: npm run tslint
      - run: npm run coverage-test

      # save caches
      - save_cache:
          paths:
            - database/node_modules
          key: v1-dependencies-database-{{ checksum "package.json" }}
